package web.utilities;

import java.io.IOException;

import web.genericLibraries.BaseClass;

public class Initialization extends BaseClass{
	
	public void initialization() throws IOException
	{
		bankPageTitles.add(pdata.getPropertydata("hsbc"));
		bankPageTitles.add(pdata.getPropertydata("barclays"));
		bankPageTitles.add(pdata.getPropertydata("monzo"));
		bankPageTitles.add(pdata.getPropertydata("nationwide"));
		bankPageTitles.add(pdata.getPropertydata("natwest"));
		bankPageTitles.add(pdata.getPropertydata("rbos"));
		bankPageTitles.add(pdata.getPropertydata("santander"));
		bankPageTitles.add(pdata.getPropertydata("lloyds"));
		bankPageTitles.add(pdata.getPropertydata("revolut"));
		bankPageTitles.add(pdata.getPropertydata("bosc"));
		bankPageTitles.add(pdata.getPropertydata("halifax"));
		bankPageTitles.add(pdata.getPropertydata("starling"));
		bankPageTitles.add(pdata.getPropertydata("tsb"));
		bankPageTitles.add(pdata.getPropertydata("fd"));
		bankPageTitles.add(pdata.getPropertydata("virgin"));
		bankPageTitles.add(pdata.getPropertydata("wise"));
		
		occupationOptions.add("Self-Employed");
		occupationOptions.add("Advertisement & Media");
		occupationOptions.add("Airline & Aviation");
		occupationOptions.add("Banking & Finance");
		occupationOptions.add("Corporate Management Professional");
		occupationOptions.add("Doctor or Medical Professional");
		occupationOptions.add("Education & Training");
		occupationOptions.add("Hospitality");
		occupationOptions.add("Software & IT");
		
		sourceOfIncome.add("Employment");
		sourceOfIncome.add("Inheritance");
		sourceOfIncome.add("Investments");
		sourceOfIncome.add("Rental Income");
		sourceOfIncome.add("Ownership of a business");
		sourceOfIncome.add("Gift");
		sourceOfIncome.add("Winnings");
		
		nationality.add("Albania");
		nationality.add("Algeria");
		nationality.add("Andorra");
		nationality.add("Angola");
		nationality.add("Antigua and Barbuda");
		nationality.add("Argentina");
		nationality.add("Armenia");
		nationality.add("Australia");
		nationality.add("Austria");
		nationality.add("Azerbaijan");
		nationality.add("Bahamas");
		nationality.add("Bahrain");
		nationality.add("Bangladesh");
		nationality.add("Barbados");
		nationality.add("Belarus");
		nationality.add("Belgium");
		nationality.add("");
		nationality.add("Benin");
		nationality.add("Bhutan");
		nationality.add("Bolivia(plurinational state of)");
		nationality.add("Bosina and Herzegovina");
		nationality.add("Botswana");
		nationality.add("Brazil");
		nationality.add("Brunei Darussalam");
		nationality.add("Bulgaria");
		nationality.add("Burkina Faso");
		nationality.add("Burundi");
		nationality.add("Cabo Verde");
		nationality.add("Cambodia");
		nationality.add("Cameroon");
		nationality.add("Canada");
		nationality.add("Central African Republic");
		nationality.add("Chad");
		nationality.add("Chile");
		nationality.add("China");
		nationality.add("Colombia");
		nationality.add("Comoros");
		nationality.add("congo");
		nationality.add("Costa Rica");
		nationality.add("cote D'Ivorie");
		nationality.add("croatia");
		nationality.add("Cuba");
		nationality.add("Cyprus");
		nationality.add("czechia");
		nationality.add("Democratic People's Republic of Korea");
		nationality.add("Democratic republic of congo");
		nationality.add("Denmark");
		nationality.add("Djibouti");
		nationality.add("Dominica");
		nationality.add("Dominican Republic");
		nationality.add("Ecuador");
		nationality.add("Egypt");
		nationality.add("El Salvador");
		nationality.add("Equatorial Guinea");
		nationality.add("Eritrea");
		nationality.add("Estonia");
		nationality.add("Eswatini");
		nationality.add("Ethiopia");
		nationality.add("Fiji");
		nationality.add("Finland");
		nationality.add("France");
		nationality.add("Gabon");
		nationality.add("Gambia (Republic of The)");
		nationality.add("Georgia");
		nationality.add("Germany");
		nationality.add("Ghana");
		nationality.add("Greece");
		nationality.add("Grenada");
		nationality.add("Guatemala");
		nationality.add("Guinea");
		nationality.add("Guinea Bissau");
		nationality.add("Guyana");
		nationality.add("Haiti");
		nationality.add("Honduras");
		nationality.add("Hungary");
		nationality.add("Iceland");
		nationality.add("India");
		nationality.add("Indonesia");
		nationality.add("Iran (Islamic Republic of)");
		nationality.add("Iraq");
		nationality.add("Ireland");
		nationality.add("Israel");
		nationality.add("Italy");
		nationality.add("Jamaica");
		nationality.add("Japan");
		nationality.add("Jordan");
		nationality.add("Kazakhstan");
		nationality.add("Kenya");
		nationality.add("Kiribati");
		nationality.add("Kuwait");
		nationality.add("Kyrgyzstan");
		nationality.add("Lao People’s Democratic Republic");
		nationality.add("Latvia");
		nationality.add("Lebanon");
		nationality.add("Lesotho");
		nationality.add("Liberia");
		nationality.add("Libya");
		nationality.add("Liechtenstein");
		nationality.add("Lithuania");
		nationality.add("Luxembourg");
		nationality.add("Madagascar");
		nationality.add("Malawi");
		nationality.add("Malaysia");
		nationality.add("Maldives");
		nationality.add("Mali");
		nationality.add("Malta");
		nationality.add("Marshall Islands");
		nationality.add("Mauritania");
		nationality.add("Mauritius");
		nationality.add("Mexico");
		nationality.add("Micronesia (Federated States of)");
		nationality.add("Monaco");
		nationality.add("Mongolia");
		nationality.add("Montenegro");
		nationality.add("Morocco");
		nationality.add("Mozambique");
		nationality.add("Myanmar");
		nationality.add("Namibia");
		nationality.add("Nauru");
		nationality.add("Nepal");
		nationality.add("Netherlands (Kingdom of the)");
		nationality.add("New Zealand");
		nationality.add("Nicaragua");
		nationality.add("Niger");
		nationality.add("Nigeria");
		nationality.add("North Macedonia");
		nationality.add("Norway");
		nationality.add("Oman");
		nationality.add("Pakistan");
		nationality.add("Palau");
		nationality.add("Panama");
		nationality.add("Papua New Guinea");
		nationality.add("Paraguay");
		nationality.add("Peru");
		nationality.add("Philippines");
		nationality.add("Poland");
		nationality.add("Portugal");
		nationality.add("Qatar");
		nationality.add("Republic of Korea");
		nationality.add("Republic of Moldova");
		nationality.add("Romania");
		nationality.add("Russian Federation");
		nationality.add("Rwanda");
		nationality.add("Saint kitts and Nevis");
		nationality.add("Saint Lucia");
		nationality.add("Saint Vincent and the Grenadines");
		nationality.add("Samoa");
		nationality.add("San Marino");
		nationality.add("Sao Tome and Principe");
		nationality.add("Saudi Arabia");
		nationality.add("Senegal");
		nationality.add("Serbia");
		nationality.add("Seychelles");
		nationality.add("Sierra Leone");
		nationality.add("Singapore");
		nationality.add("Slovakia");
		nationality.add("Slovenia");
		nationality.add("Solomon Islands");
		nationality.add("Somalia");
		nationality.add("South Africa");
		nationality.add("South Sudan");
		nationality.add("Spain");
		nationality.add("Sri Lanka");
		nationality.add("Sudan");
		nationality.add("Suriname");
		nationality.add("Sweden");
		nationality.add("Switzerland");
		nationality.add("Syrian Arab Republic");
		nationality.add("Tajikistan");
		nationality.add("Thailand");
		nationality.add("Timor-Leste");
		nationality.add("Togo");
		nationality.add("Tonga");
		nationality.add("Trinidad and Tobago");
		nationality.add("Tunisia");
		nationality.add("Türkiye");
		nationality.add("Turkmenistan");
		nationality.add("Tuvalu");
		nationality.add("Uganda");
		nationality.add("Ukraine");
		nationality.add("United Arab Emirates");
		nationality.add("United Kingdom");
		nationality.add("United Republic of Tanzania");
		nationality.add("United States of America");
		nationality.add("Uruguay");
		nationality.add("Uzbekistan");
		nationality.add("Vanuatu");
		nationality.add("Venezuela, Bolivarian Republic of");
		nationality.add("Viet Nam");
		nationality.add("Yemen");
		nationality.add("Zambia");
		nationality.add("Zimbabwe");
	}

}
